import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

// ============================================================
// EXPORT TRADING PLAN
// GET /api/screener/export?format=text&mode=combo&date=2025-04-25
// GET /api/screener/export?format=pdf&mode=combo&date=2025-04-25
// ============================================================

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

function formatRupiah(n: number): string {
  return n?.toLocaleString("id-ID") || "0";
}

function formatDate(isoDate: string): string {
  return new Date(isoDate).toLocaleDateString("id-ID", {
    weekday: "long", day: "numeric", month: "long", year: "numeric",
  });
}

function buildTelegramText(results: Array<{
  ticker: string;
  score: number;
  priority: string;
  signals: string[];
  trading_plan: {
    entryLow: number; entryHigh: number;
    tp1: number; tp2: number;
    cutLoss: number; rrRatio: number;
  };
  avg_bandar: number;
  rsi: number;
  volume_multiplier: number;
  screener_mode: string;
}>, date: string, mode: string): string {
  const dateStr = formatDate(date + "T00:00:00");
  const modeLabel: Record<string, string> = {
    combo: "Combo Score", bandar: "Akumulasi Bandar", oversold: "Oversold/Bounce",
    volume_spike: "Volume Spike", breakout: "Breakout", bsjp: "BSJP",
  };

  let text = `📋 *TRADING PLAN HARIAN*\n`;
  text += `📅 ${dateStr}\n`;
  text += `🎯 Mode: ${modeLabel[mode] || mode.toUpperCase()}\n`;
  text += `${"━".repeat(30)}\n\n`;

  const high = results.filter(r => r.priority === "HIGH");
  const medium = results.filter(r => r.priority === "MEDIUM");
  const low = results.filter(r => r.priority === "LOW");

  function addSection(label: string, items: typeof results, emoji: string) {
    if (!items.length) return;
    text += `${emoji} *${label}* (${items.length} saham)\n`;
    text += `${"─".repeat(25)}\n`;
    for (const r of items) {
      const plan = r.trading_plan;
      const upside1 = plan.tp1 && r.trading_plan.entryHigh
        ? (((plan.tp1 - r.trading_plan.entryHigh) / r.trading_plan.entryHigh) * 100).toFixed(1)
        : "0.0";
      const downside = plan.cutLoss && r.trading_plan.entryLow
        ? (((plan.cutLoss - r.trading_plan.entryLow) / r.trading_plan.entryLow) * 100).toFixed(1)
        : "0.0";

      text += `\n*${r.ticker}* — Skor ${r.score}/100\n`;
      text += `Sinyal: ${r.signals?.slice(0, 2).join(", ")}\n`;
      text += `Entry : ${formatRupiah(plan.entryLow)}–${formatRupiah(plan.entryHigh)}\n`;
      text += `TP1   : ${formatRupiah(plan.tp1)} (+${upside1}%)\n`;
      text += `TP2   : ${formatRupiah(plan.tp2)}\n`;
      text += `CL    : ${formatRupiah(plan.cutLoss)} (${downside}%)\n`;
      text += `R/R   : 1:${plan.rrRatio} | RSI: ${r.rsi?.toFixed(0) || "-"}\n`;
      if (r.avg_bandar) text += `Avg Bandar: ${formatRupiah(r.avg_bandar)}\n`;
    }
    text += "\n";
  }

  addSection("HIGH PRIORITY", high, "🔥");
  addSection("MEDIUM PRIORITY", medium, "⚡");
  addSection("LOW PRIORITY", low, "📌");

  text += `${"━".repeat(30)}\n`;
  text += `_Generated by Adimology Screener_`;

  return text;
}

function buildHtmlPdf(results: Parameters<typeof buildTelegramText>[0], date: string, mode: string): string {
  const dateStr = formatDate(date + "T00:00:00");
  const modeLabel: Record<string, string> = {
    combo: "Combo Score", bandar: "Akumulasi Bandar", oversold: "Oversold/Bounce",
    volume_spike: "Volume Spike", breakout: "Breakout", bsjp: "BSJP",
  };

  const priorityColor: Record<string, string> = {
    HIGH: "#10b981", MEDIUM: "#f59e0b", LOW: "#64748b",
  };

  const rows = results.map(r => {
    const plan = r.trading_plan;
    const upside1 = plan.tp1 && plan.entryHigh
      ? (((plan.tp1 - plan.entryHigh) / plan.entryHigh) * 100).toFixed(1)
      : "0.0";
    const upside2 = plan.tp2 && plan.entryHigh
      ? (((plan.tp2 - plan.entryHigh) / plan.entryHigh) * 100).toFixed(1)
      : "0.0";
    const downside = plan.cutLoss && plan.entryLow
      ? (((plan.cutLoss - plan.entryLow) / plan.entryLow) * 100).toFixed(1)
      : "0.0";
    const color = priorityColor[r.priority] || "#64748b";

    return `
      <tr>
        <td class="ticker">${r.ticker}</td>
        <td><span class="priority-badge" style="background:${color}20;color:${color};border:1px solid ${color}40">${r.priority}</span></td>
        <td class="score">${r.score}</td>
        <td class="signals">${r.signals?.slice(0, 2).join(", ") || "-"}</td>
        <td class="number">${formatRupiah(plan.entryLow)}–${formatRupiah(plan.entryHigh)}</td>
        <td class="number green">
          ${formatRupiah(plan.tp1)}<br>
          <small style="color:#6ee7b7">+${upside1}%</small>
        </td>
        <td class="number green">
          ${formatRupiah(plan.tp2)}<br>
          <small style="color:#6ee7b7">+${upside2}%</small>
        </td>
        <td class="number red">
          ${formatRupiah(plan.cutLoss)}<br>
          <small style="color:#fca5a5">${downside}%</small>
        </td>
        <td class="number">${plan.rrRatio}</td>
        <td class="number">${r.avg_bandar ? formatRupiah(r.avg_bandar) : "-"}</td>
        <td class="number">${r.rsi?.toFixed(0) || "-"}</td>
        <td class="number">${r.volume_multiplier ? r.volume_multiplier + "×" : "-"}</td>
      </tr>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }
    .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 24px; border-bottom: 1px solid #334155; padding-bottom: 16px; }
    .title { font-size: 22px; font-weight: 700; color: #fff; }
    .subtitle { font-size: 13px; color: #64748b; margin-top: 4px; }
    .badge { font-size: 12px; background: #6366f120; color: #818cf8; border: 1px solid #6366f140; padding: 4px 12px; border-radius: 20px; }
    .stats { display: flex; gap: 16px; margin-bottom: 20px; }
    .stat { background: #1e293b; border: 1px solid #334155; border-radius: 10px; padding: 12px 20px; text-align: center; flex: 1; }
    .stat-val { font-size: 24px; font-weight: 700; color: #818cf8; }
    .stat-label { font-size: 11px; color: #64748b; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    thead tr { background: #1e293b; }
    th { padding: 10px 8px; text-align: left; font-size: 10px; text-transform: uppercase; color: #64748b; font-weight: 600; letter-spacing: 0.5px; border-bottom: 1px solid #334155; }
    tbody tr { border-bottom: 1px solid #1e293b; }
    tbody tr:hover { background: #1e293b50; }
    td { padding: 9px 8px; vertical-align: middle; }
    .ticker { font-family: monospace; font-weight: 700; font-size: 14px; color: #fff; }
    .score { font-weight: 700; color: #818cf8; font-family: monospace; }
    .signals { color: #94a3b8; font-size: 11px; max-width: 160px; }
    .number { font-family: monospace; color: #cbd5e1; font-size: 11px; }
    .green { color: #34d399 !important; }
    .red { color: #f87171 !important; }
    .priority-badge { font-size: 10px; padding: 2px 8px; border-radius: 20px; font-weight: 600; white-space: nowrap; }
    .footer { margin-top: 20px; text-align: center; font-size: 11px; color: #475569; border-top: 1px solid #1e293b; padding-top: 12px; }
    @media print { body { padding: 12px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="title">📋 Trading Plan Harian</div>
      <div class="subtitle">${dateStr} &nbsp;·&nbsp; Mode: ${modeLabel[mode] || mode}</div>
    </div>
    <div class="badge">Adimology Screener</div>
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-val">${results.length}</div>
      <div class="stat-label">Total Saham</div>
    </div>
    <div class="stat">
      <div class="stat-val" style="color:#10b981">${results.filter(r => r.priority === "HIGH").length}</div>
      <div class="stat-label">HIGH Priority</div>
    </div>
    <div class="stat">
      <div class="stat-val" style="color:#f59e0b">${results.filter(r => r.priority === "MEDIUM").length}</div>
      <div class="stat-label">MEDIUM Priority</div>
    </div>
    <div class="stat">
      <div class="stat-val">${results.length ? Math.round(results.reduce((a, r) => a + r.score, 0) / results.length) : 0}</div>
      <div class="stat-label">Avg Score</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Ticker</th><th>Priority</th><th>Score</th><th>Sinyal</th>
        <th>Entry Zone</th><th>TP1</th><th>TP2</th><th>Cut Loss</th>
        <th>R/R</th><th>Avg Bandar</th><th>RSI</th><th>Volume</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    Generated ${new Date().toLocaleString("id-ID")} · Adimology Platform · Data: Stockbit + Yahoo Finance
  </div>
</body>
</html>`;
}

export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const format = url.searchParams.get("format") || "text"; // text | html | json
  const mode = url.searchParams.get("mode") || "combo";
  const date = url.searchParams.get("date") || new Date().toISOString().split("T")[0];
  const limit = parseInt(url.searchParams.get("limit") || "30");

  const { data, error } = await supabase
    .from("screener_results")
    .select("*")
    .eq("screener_mode", mode)
    .gte("created_at", `${date}T00:00:00`)
    .lte("created_at", `${date}T23:59:59`)
    .order("score", { ascending: false })
    .limit(limit);

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  if (!data?.length) return NextResponse.json({ error: "Tidak ada data untuk tanggal ini", date, mode }, { status: 404 });

  if (format === "text") {
    const text = buildTelegramText(data, date, mode);
    return new Response(text, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="trading-plan-${date}.txt"`,
      },
    });
  }

  if (format === "html") {
    const html = buildHtmlPdf(data, date, mode);
    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="trading-plan-${date}.html"`,
      },
    });
  }

  return NextResponse.json({ results: data, date, mode, total: data.length });
}
